import React, { createContext, useContext, useState, useEffect } from 'react';

const AppContext = createContext();

export const TRANSLATIONS = {
  en: {
    portalTitle: 'india.gov.in',
    portalTitleScript: 'india.gov.in',
    portalTitleSub: 'National Portal of India',
    nationalPortal: 'National Portal of India',
    tagline: 'Where Government Information Converges',
    govIndia: 'Government of India',
    bharatSarkar: 'भारत सरकार',
    searchPlaceholder: 'Search for schemes, welfare policies, departments...',
    allCategories: 'All Categories',
    searchButton: 'Search',
    searchHere: 'Search Here',
    trendingSchemesLabel: 'Key National Schemes :',
    servicesCount: 'Online Services',
    schemesCount: 'Govt Schemes',
    citizenCount: 'Citizen Engagements',
    placesCount: 'Tourist Places',
    odopCount: 'ODOP Products',
    categoriesCount: 'Information Categories',
    pmQuote: "India's Digital Public Infrastructure has demonstrated how technology can expand opportunity, improve governance, boost financial inclusion and deliver services for hundreds of millions of people.",
    pmAttribution: 'National Assembly of Seychelles',
    pmDate: '28 June 2026',
    schemesTitle: 'Government Schemes & Welfare Programs',
    schemesSubtitle: 'Access and simulate major Government of India central schemes directly in the AI Policy Simulator.',
    allSchemes: 'All Schemes',
    viewAll: 'View All Schemes',
    officialPortal: 'Official Portal',
    simulateBtn: 'Simulate & Edit Scheme in Analyzer →',
    targetCohort: 'Target',
    budget: 'Budget',
    filterSchemes: 'Filter national schemes...',
    methodologyTitle: 'Core Methodology & 4-Layer Architecture',
    methodologySubtitle: 'Decoupled, high-rigor analytical architecture ensuring verified decision-support without hallucination.',
    launchSimulatorBtn: 'Launch Policy Maker & Scheme Analyzer Workspace →',
    layer1Title: 'GraphRAG Policy Knowledge Graph',
    layer1Desc: 'Structured semantic mapping of Indian welfare policies, demographic cohorts (SC/ST/OBC, gender), line ministries, and target welfare KPIs into an auditable knowledge graph.',
    layer2Title: 'Mathematical Multipliers & Impact Engine',
    layer2Desc: 'Calculates empirical elasticities across poverty alleviation, rural wage multipliers, nutritional stunting mitigation, and fiscal feasibility across states.',
    layer3Title: 'Monte Carlo Stochastic Uncertainty',
    layer3Desc: 'Runs 500+ probabilistic iterations across GDP growth variances, inflation shocks, and monsoon rainfall fluctuations to yield robust 95% confidence intervals.',
    layer4Title: 'RL PPO Optimization & LLM Policy Synthesis',
    layer4Desc: 'Proximal Policy Optimization explores 10 policy levers simultaneously to discover Pareto-optimal social return frontiers, synthesized with Groq Llama-3.3-70B.',
    home: 'Home',
    policyMaker: 'Policy Maker & Scheme Analyzer',
    customMode: 'Custom Policy Creator',
    existingMode: 'Existing Scheme Editor & Evaluator',
    selectScheme: 'Select Scheme to Amend & Simulate',
    policyAmendmentPrompt: 'Policy Amendment & Strategic Objectives',
    policyAmendmentPlaceholder: 'Describe the targeted beneficiaries, state-level implementation roadmap, or amendments...',
    configureLevers: 'Configure 10 Policy Levers',
    analyzeBtn: 'Analyze Policy Impact & Generate AI Report',
    analyzing: 'Running Monte Carlo & AI Synthesis...',
    optimizeBtn: 'Suggest Optimal Settings (PPO AI)',
    optimizing: 'Optimizing Policy Pareto Frontier...',
    effectivenessScore: 'Policy Effectiveness Score',
    fiscalOutlay: 'Total Fiscal Outlay',
    sustainabilityScore: '5-Yr Sustainability Score',
    beneficiaries: 'Primary Beneficiaries',
    sectoralBreakdown: 'Sectoral & Demographic Impact Breakdown',
    genderImpact: 'Gender Equity & Women Participation',
    casteImpact: 'Social Cohort Gains (SC/ST/OBC)',
    childFamilyImpact: 'Child Malnutrition & Family Welfare',
    stateMapTitle: '28-State Impact Choropleth Map',
    demographicChartTitle: 'Demographic Income Gain (95% CI)',
    aiAdvisorTitle: 'AI Senior Policy Advisor — Executive Synthesis',
    executiveVerdict: 'Executive Verdict',
    risksAndMitigations: 'Fiscal & Regional Risks',
    strategicRecommendations: 'Strategic Implementation Recommendations',
    contentSources: 'Content Sources',
    viewOnMobile: 'View on Mobile',
    followUs: 'Follow Us',
    translationDisclaimerTitle: 'Translation Disclaimer',
    translationDisclaimerText: 'Translations of the content into languages other than English are generated using automated tools and may not always be accurate. These translations are provided for informational purposes only and should not be considered authoritative.',
    nicTitle: 'National Informatics Centre (NIC)',
    nicText: 'India Portal is developed under the Digital India Programme to provide citizens with open and easy access to information. It is designed, developed, and maintained by the National Informatics Centre (NIC), under the Ministry of Electronics & Information Technology, Government of India. The content available on India Portal is owned and managed by the respective Ministries and Departments.',
    lastUpdated: 'Last reviewed and updated on 06 October 2026',
    languageName: 'English'
  },
  hi: {
    portalTitle: 'bharat.gov.in',
    portalTitleScript: 'भारत.सरकार.इन',
    portalTitleSub: 'भारत का राष्ट्रीय पोर्टल',
    nationalPortal: 'भारत का राष्ट्रीय पोर्टल',
    tagline: 'जहाँ सरकारी जानकारी का संगम होता है',
    govIndia: 'भारत सरकार',
    bharatSarkar: 'भारत सरकार',
    searchPlaceholder: 'योजनाओं, कल्याणकारी नीतियों, विभागों के लिए खोजें...',
    allCategories: 'सभी श्रेणियाँ',
    searchButton: 'खोजें',
    searchHere: 'यहाँ खोजें',
    trendingSchemesLabel: 'प्रमुख राष्ट्रीय योजनाएं :',
    servicesCount: 'ऑनलाइन सेवाएं',
    schemesCount: 'सरकारी योजनाएं',
    citizenCount: 'नागरिक सहभागिता',
    placesCount: 'पर्यटन स्थल',
    odopCount: 'एक जिला एक उत्पाद (ODOP)',
    categoriesCount: 'सूचना श्रेणियाँ',
    pmQuote: "भारत के डिजिटल सार्वजनिक अवसंरचना ने प्रदर्शित किया है कि तकनीक कैसे अवसर बढ़ा सकती है, शासन में सुधार कर सकती है, वित्तीय समावेशन को बढ़ावा दे सकती है और करोड़ों लोगों तक सेवाएं पहुंचा सकती है।",
    pmAttribution: 'सेशेल्स की नेशनल असेंबली',
    pmDate: '28 जून 2026',
    schemesTitle: 'सरकारी योजनाएं एवं कल्याणकारी कार्यक्रम',
    schemesSubtitle: 'एआई नीति सिम्युलेटर में सीधे प्रमुख भारत सरकार की योजनाओं का अनुकरण और संपादन करें।',
    allSchemes: 'सभी योजनाएं',
    viewAll: 'सभी योजनाएं देखें',
    officialPortal: 'आधिकारिक पोर्टल',
    simulateBtn: 'विश्लेषक में योजना का अनुकरण और संपादन करें →',
    targetCohort: 'लक्षित वर्ग',
    budget: 'बजट',
    filterSchemes: 'राष्ट्रीय योजनाओं को फ़िल्टर करें...',
    methodologyTitle: 'मुख्य कार्यप्रणाली और 4-स्तरीय वास्तुकला',
    methodologySubtitle: 'सत्यापित निर्णय-समर्थन सुनिश्चित करने वाला उच्च-सटीक विश्लेषणात्मक ढांचा।',
    launchSimulatorBtn: 'नीति निर्माता और योजना विश्लेषक कार्यक्षेत्र शुरू करें →',
    layer1Title: 'ग्राफ-आरएजी नीति ज्ञान ग्राफ',
    layer1Desc: 'भारतीय कल्याणकारी नीतियों, जनसांख्यिकीय समूहों (एससी/एसटी/ओबीसी, लिंग) और मंत्रालयों का संरचित ज्ञान ग्राफ।',
    layer2Title: 'गणितीय गुणक एवं प्रभाव इंजन',
    layer2Desc: 'गरीबी उन्मूलन, ग्रामीण मजदूरी गुणक और पोषण में सुधार के लिए सटीक गणितीय मॉडल।',
    layer3Title: 'मोंटे कार्लो स्टोकेस्टिक अनिश्चितता सिमुलेशन',
    layer3Desc: 'मजबूत 95% विश्वास अंतराल प्राप्त करने के लिए जीडीपी विकास और मानसून के 500+ सिमुलेशन पुनरावृत्तियां।',
    layer4Title: 'आरएल पीपीओ अनुकूलन एवं एलएलएम नीति संश्लेषण',
    layer4Desc: 'प्रॉक्सिमल पॉलिसी ऑप्टिमाइज़ेशन (PPO) 10 नीतिगत लीवरों की इष्टतम सेटिंग्स खोजता है।',
    home: 'होम',
    policyMaker: 'नीति निर्माता और योजना विश्लेषक',
    customMode: 'कस्टम नीति निर्माता',
    existingMode: 'मौजूदा योजना संपादक और मूल्यांकनकर्ता',
    selectScheme: 'संशोधन एवं अनुकरण के लिए योजना चुनें',
    policyAmendmentPrompt: 'नीति संशोधन एवं रणनीतिक उद्देश्य',
    policyAmendmentPlaceholder: 'लक्षित लाभार्थियों, राज्य-स्तरीय कार्यान्वयन रोडमैप या संशोधनों का वर्णन करें...',
    configureLevers: '10 नीतिगत लीवरों को समायोजित करें',
    analyzeBtn: 'नीति प्रभाव का विश्लेषण करें और एआई रिपोर्ट बनाएं',
    analyzing: 'मोंटे कार्लो एवं एआई विश्लेषण जारी है...',
    optimizeBtn: 'इष्टतम सेटिंग्स सुझाएं (पीपीओ एआई)',
    optimizing: 'नीतिगत सीमा का अनुकूलन किया जा रहा है...',
    effectivenessScore: 'नीति प्रभावशीलता स्कोर',
    fiscalOutlay: 'कुल वित्तीय परिव्यय',
    sustainabilityScore: '5-वर्षीय स्थिरता स्कोर',
    beneficiaries: 'प्राथमिक लाभार्थी',
    sectoralBreakdown: 'क्षेत्रीय और जनसांख्यिकीय प्रभाव विवरण',
    genderImpact: 'लैंगिक समानता एवं महिला सहभागिता',
    casteImpact: 'सामाजिक वर्ग लाभ (एससी/एसटी/ओबीसी)',
    childFamilyImpact: 'बाल कुपोषण निवारण एवं पारिवारिक कल्याण',
    stateMapTitle: '28-राज्य प्रभाव कोरोप्लेथ मानचित्र',
    demographicChartTitle: 'जनसांख्यिकीय आय वृद्धि (95% सीआई)',
    aiAdvisorTitle: 'एआई वरिष्ठ नीति सलाहकार — कार्यकारी निष्कर्ष',
    executiveVerdict: 'कार्यकारी निष्कर्ष',
    risksAndMitigations: 'वित्तीय एवं क्षेत्रीय जोखिम',
    strategicRecommendations: 'रणनीतिक कार्यान्वयन सिफारिशें',
    contentSources: 'सामग्री स्रोत',
    viewOnMobile: 'मोबाइल पर देखें',
    followUs: 'हमें फॉलो करें',
    translationDisclaimerTitle: 'अनुवाद अस्वीकरण',
    translationDisclaimerText: 'अंग्रेजी के अलावा अन्य भाषाओं में सामग्री का अनुवाद स्वचालित उपकरणों द्वारा तैयार किया जाता है और यह केवल सूचनात्मक उद्देश्यों के लिए है।',
    nicTitle: 'राष्ट्रीय सूचना विज्ञान केंद्र (एनआईसी)',
    nicText: 'इंडिया पोर्टल डिजिटल इंडिया कार्यक्रम के तहत विकसित किया गया है। इसे इलेक्ट्रॉनिक्स और सूचना प्रौद्योगिकी मंत्रालय, भारत सरकार के तहत राष्ट्रीय सूचना विज्ञान केंद्र (एनआईसी) द्वारा डिजाइन और बनाए रखा गया है।',
    lastUpdated: 'अंतिम समीक्षा एवं अद्यतन 06 अक्टूबर 2026',
    languageName: 'हिन्दी'
  },
  ta: {
    portalTitle: 'bharat.gov.in',
    portalTitleScript: 'பாரதம்.அரசு.இன்',
    portalTitleSub: 'இந்தியாவின் தேசிய போர்டல்',
    nationalPortal: 'இந்தியாவின் தேசிய போர்டல்',
    tagline: 'அரசு தகவல்கள் ஒன்றிணையும் தளம்',
    govIndia: 'இந்திய அரசு',
    bharatSarkar: 'பாரத அரசு',
    searchPlaceholder: 'திட்டங்கள், நலக் கொள்கைகள், துறைகளைத் தேடுங்கள்...',
    allCategories: 'அனைத்து பிரிவுகளும்',
    searchButton: 'தேடுக',
    searchHere: 'இங்கே தேடுக',
    trendingSchemesLabel: 'முக்கிய தேசிய திட்டங்கள் :',
    servicesCount: 'ஆன்லைன் சேவைகள்',
    schemesCount: 'அரசு திட்டங்கள்',
    citizenCount: 'குடிமக்கள் ஈடுபாடு',
    placesCount: 'சுற்றுலா தலங்கள்',
    odopCount: 'ODOP தயாரிப்புகள்',
    categoriesCount: 'தகவல் பிரிவுகள்',
    pmQuote: "இந்தியாவின் டிஜிட்டல் பொது உள்கட்டமைப்பு, தொழில்நுட்பம் எவ்வாறு வாய்ப்புகளை விரிவுபடுத்தவும், நிர்வாகத்தை மேம்படுத்தவும், நிதி உள்ளடக்கத்தை ஊக்குவிக்கவும் மற்றும் கோடிக்கணக்கான மக்களுக்கு சேவைகளை வழங்கவும் முடியும் என்பதை நிரூபித்துள்ளது.",
    pmAttribution: 'சீஷெல்ஸ் தேசிய சட்டமன்றம்',
    pmDate: '28 ஜூன் 2026',
    schemesTitle: 'அரசு திட்டங்கள் மற்றும் நலன்புரி திட்டங்கள்',
    schemesSubtitle: 'AI கொள்கை சிமுலேட்டரில் நேரடியாக இந்திய அரசின் மத்திய திட்டங்களை உருவகப்படுத்துங்கள்.',
    allSchemes: 'அனைத்து திட்டங்கள்',
    viewAll: 'அனைத்து திட்டங்களையும் காண்க',
    officialPortal: 'அதிகாரப்பூர்வ தளம்',
    simulateBtn: 'ஆய்வுக் கருவியில் திட்டத்தை உருவகப்படுத்தி திருத்துக →',
    targetCohort: 'இலக்கு',
    budget: 'பட்ஜெட்',
    filterSchemes: 'தேசிய திட்டங்களை வடிகட்டுக...',
    methodologyTitle: 'முக்கிய வழிமுறை & 4-அடுக்கு கட்டமைப்பு',
    methodologySubtitle: 'சரிபார்க்கப்பட்ட முடிவெடுக்கும் ஆதரவை உறுதி செய்யும் உயர்-துல்லிய கட்டமைப்பு.',
    launchSimulatorBtn: 'கொள்கை வகுப்பாளர் & திட்ட பகுப்பாய்வி பணியிடத்தைத் தொடங்கவும் →',
    layer1Title: 'GraphRAG கொள்கை அறிவு வரைபடம்',
    layer1Desc: 'இந்திய நலக் கொள்கைகள் மற்றும் மக்கள்தொகை குழுக்களின் கட்டமைக்கப்பட்ட அறிவு வரைபடம்.',
    layer2Title: 'கணித பெருக்கிகள் மற்றும் தாக்க இயந்திரம்',
    layer2Desc: 'வறுமை ஒழிப்பு மற்றும் ஊரக கூலி பெருக்கிகளுக்கான துல்லியமான கணித மாதிரி.',
    layer3Title: 'மான்டே கார்லோ நிச்சயமற்ற உருவகப்படுத்துதல்',
    layer3Desc: '95% நம்பிக்கை இடைவெளிகளை வழங்க 500+ நிகழ்தகவு சோதனைகள்.',
    layer4Title: 'RL PPO உகப்பாக்கம் மற்றும் LLM கொள்கை தொகுப்பு',
    layer4Desc: '10 கொள்கை நெம்புகோல்களை ஒரே நேரத்தில் ஆய்வு செய்து உகந்த முடிவுகளைக் கண்டறிகிறது.',
    home: 'முகப்பு',
    policyMaker: 'கொள்கை வகுப்பாளர் & திட்ட பகுப்பாய்வி',
    customMode: 'தனிப்பயன் கொள்கை உருவாக்குநர்',
    existingMode: 'தற்போதுள்ள திட்ட திருத்தி & மதிப்பீட்டாளர்',
    selectScheme: 'திருத்த மற்றும் உருவகப்படுத்த திட்டத்தைத் தேர்ந்தெடுக்கவும்',
    policyAmendmentPrompt: 'கொள்கை திருத்தம் & மூலோபாய நோக்கங்கள்',
    policyAmendmentPlaceholder: 'இலக்கு பயனாளிகள் மற்றும் செயல்படுத்தும் வழிகாட்டலை விவரிக்கவும்...',
    configureLevers: '10 கொள்கை நெம்புகோல்களை உள்ளமைக்கவும்',
    analyzeBtn: 'கொள்கை தாக்கத்தை பகுப்பாய்வு செய்து AI அறிக்கை உருவாக்கவும்',
    analyzing: 'உருவகப்படுத்துதல் நடைபெறுகிறது...',
    optimizeBtn: 'உகந்த அமைப்புகளைப் பரிந்துரைக்கவும் (PPO AI)',
    optimizing: 'உகப்பாக்கம் செய்யப்படுகிறது...',
    effectivenessScore: 'கொள்கை செயல்திறன் மதிப்பீடு',
    fiscalOutlay: 'மொத்த நிதி ஒதுக்கீடு',
    sustainabilityScore: '5-ஆண்டு நிலைத்தன்மை மதிப்பீடு',
    beneficiaries: 'முதன்மை பயனாளிகள்',
    sectoralBreakdown: 'துறை மற்றும் மக்கள்தொகை தாக்க முறிவு',
    genderImpact: 'பாலின சமத்துவம் & மகளிர் பங்கேற்பு',
    casteImpact: 'சமூகப் பிரிவு ஆதாயங்கள் (SC/ST/OBC)',
    childFamilyImpact: 'குழந்தைகள் ஊட்டச்சத்து & குடும்ப நல்வாழ்வு',
    stateMapTitle: '28-மாநில தாக்க வரைபடம்',
    demographicChartTitle: 'மக்கள்தொகை வருமான உயர்வு (95% CI)',
    aiAdvisorTitle: 'AI மூத்த கொள்கை ஆலோசகர் — நிர்வாக தொகுப்பு',
    executiveVerdict: 'நிர்வாக தீர்ப்பு',
    risksAndMitigations: 'நிதி மற்றும் பிராந்திய அபாயங்கள்',
    strategicRecommendations: 'மூலோபாய அமலாக்கப் பரிந்துரைகள்',
    contentSources: 'உள்ளடக்க ஆதாரங்கள்',
    viewOnMobile: 'மொபைலில் பார்க்க',
    followUs: 'எங்களை பின்தொடரவும்',
    translationDisclaimerTitle: 'மொழிபெயர்ப்பு மறுப்பு',
    translationDisclaimerText: 'ஆங்கிலம் தவிர மற்ற மொழிகளுக்கான மொழிபெயர்ப்புகள் தகவல் நோக்கங்களுக்காக மட்டுமே வழங்கப்படுகின்றன.',
    nicTitle: 'தேசிய தகவல் மையம் (NIC)',
    nicText: 'இந்திய போர்டல் டிஜிட்டல் இந்தியா திட்டத்தின் கீழ் உருவாக்கப்பட்டு தேசிய தகவல் மையத்தால் (NIC) பராமரிக்கப்படுகிறது.',
    lastUpdated: 'கடைசியாக மதிப்பாய்வு செய்யப்பட்டு புதுப்பிக்கப்பட்டது 06 அக்டோபர் 2026',
    languageName: 'தமிழ்'
  }
};

export function AppProvider({ children }) {
  const [language, setLanguage] = useState('en'); // 'en' -> 'hi' -> 'ta' -> 'en'
  const [theme, setTheme] = useState('light'); // 'light' | 'dark'

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    if (theme === 'dark') {
      document.body.classList.add('dark-mode');
    } else {
      document.body.classList.remove('dark-mode');
    }
  }, [theme]);

  const toggleLanguage = () => {
    setLanguage(prev => {
      if (prev === 'en') return 'hi';
      if (prev === 'hi') return 'ta';
      return 'en';
    });
  };

  const toggleTheme = () => {
    setTheme(prev => (prev === 'light' ? 'dark' : 'light'));
  };

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <AppContext.Provider value={{ language, setLanguage, toggleLanguage, theme, setTheme, toggleTheme, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  return useContext(AppContext);
}
